name: PR

on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  demo-ui-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: ./demo-ui
        run: npm ci
      - name: Build
        working-directory: ./demo-ui
        run: npm run build --if-present
      - name: Run tests
        working-directory: ./demo-ui
        run: npm test run
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: demo-ui-test-results
          path: demo-ui/test-results/junit.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success()
        with:
          files: |
            demo-ui/test-results/junit.xml
  publish:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    needs: [demo-ui-tests] # Add server tests when implemented
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
      - name: Log in to the Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push images to registries
        run: sbt "buildClient; toplBtcBridge / Docker / publish"
        env:
          DOCKER_PUBLISH: true
          RELEASE_PUBLISH: true